### ISSUE TITLE
Agent list_tools() throws exception on filtering out tools

### ISSUE THREAD

**Issue by BryceRyan** [lastmile-ai/mcp-agent#558]
mcp_agent/agents/agent.py:713

```python
# Log detailed reasons at trace level (if trace logging is available)
if logger.isEnabledFor(10):  # TRACE level is usually 10
    for tool_name, reason in filtered_out_tools:
        logger.log(10, f"Filtered out '{tool_name}': {reason}")
```

logger.isEnabledFor is not a function, so it is crashing.  Unsure if this was a hallucination of something or a legacy logger that was replaced, so didn't want to just open a PR for however you all do trace logging these days.

**Comment by saqadri** [comment]
Great catch @BryceRyan. Looks like a bad merge. I can hotfix today, but if you can create a PR I would love for your contribution and will accept the fix!

**Comment by BryceRyan** [comment]
Sure, I can just patch it so it doesn't crash.

**Comment by saqadri** [comment]
Amazing, thank you @BryceRyan for reporting **and** fixing the issue! Welcome to the contributors list :). I've published a minor version bump and 0.1.35 won't have this issue. Please keep more feedback and fixes coming! Would also love your help dogfooding some stuff we are working on separately! (you can reach me on discord or at my email anytime)
