### ISSUE TITLE
Support max_completion_tokens for reasoning models on AzureAugmentLLM

### ISSUE THREAD

**Issue by AgidensKevinG** [lastmile-ai/mcp-agent#541]
I'm trying to make a small PoC in Streamlit to test a MCP Server a colleague of my made using our Azure AI Foundry LLM's. Everything works fine with GPT-4.1, but when trying to use a reasoning model (gpt-5, gpt-5-mini, gpt-5-nano) I get following warning: `Initial Azure API call failed: (unsupported_parameter) Unsupported parameter: 'max_tokens' is not supported with this model. Use 'max_completion_tokens' instead.`

After digging through the code I found [this issue](https://github.com/lastmile-ai/mcp-agent/issues/138]/PR) where it fixes the same problem in OpenAIAugmentedLLM.
But when trying to see if I can "fix" it myself locally by doing a same argument switch to the AzureAugmentedLLM code, I get stuck with:

```
[INFO] 2025-10-06T11:20:35 mcp_agent.workflows.llm.augmented_llm_azure.aline2 - Using reasoning model 'gpt-5-mini' with 'medium' reasoning effort
[ERROR] 2025-10-06T11:20:35 mcp_agent.executor.executor - Error executing task: Session.request() got an unexpected keyword argument 'max_completion_tokens'
[ERROR] 2025-10-06T11:20:35 mcp_agent.workflows.llm.augmented_llm_azure.aline2 - Error: Session.request() got an unexpected keyword argument 'max_completion_tokens'
```

After trying to rabbithole into the executor part, I found it a bit too deep and get completely lost 🙁

> Can you please file a GitHub issue in the repo for this, and I will get a patch update published today with the fix. We fixed it for regular OpenAI but I think missed it for azure OpenAI

Thanks for the lightning fast response on Discord :)

**Comment by StreetLamb** [comment]
Hi @AgidensKevinG, thanks for reporting the bug! I just pushed a fix that should resolve your issue :)

**Comment by saqadri** [comment]
Fixed by #542

**Comment by AgidensKevinG** [comment]
> Hi [@AgidensKevinG](https://github.com/AgidensKevinG), thanks for reporting the bug! I just pushed a fix that should resolve your issue :)

Works like a charm, thank you for the incredible quick fix :) I checked the PR, that one I could not have come up with myself :D
